spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    url: jdbc:h2:~/constructiondb;AUTO_SERVER=TRUE
    user: sa
    clean-on-validation-error: true
    locations: classpath:db/specific/h2

datasource:
  primary:
    url: jdbc:h2:~/constructiondb
    username: sa
    password:
    driverClassName: org.h2.Driver

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect